### ISSUE TITLE
Talk about caching

### ISSUE THREAD

**Issue by DavidBruant** [w3ctag/polyfills#10]
The document does not mention HTTP caching

**Comment by triblondon** [comment]
What should it say? :-)

**Comment by DavidBruant** [comment]
That the polyfills should be aggressively cached?
Maybe somebody (you? ;-) ) already have results on what a good value for `Expire` should be?

**Comment by triblondon** [comment]
Opened PR and welcome feedback there
https://github.com/w3ctag/polyfills/pull/21
