### ISSUE TITLE
Provide a definition of a polyfill

### ISSUE THREAD

**Issue by DavidBruant** [w3ctag/polyfills#11]
The abstract starts with the word "polyfill" but does not define it.
I regularly give JS trainings and people do not know what it is even when they ask for the "advanced" training.

**Comment by DavidBruant** [comment]
oh yes, I see it in the `Nomenclature` section. Maybe a `Definitions` should be more appropriate, I don't know

**Comment by triblondon** [comment]
I think this is largely covered in #1
