### ISSUE TITLE
Discussion on "Don't create globals with common names for speculative polyfills"

### ISSUE THREAD

**Issue by DavidBruant** [w3ctag/polyfills#13]
A while ago, [I suggested](https://lists.w3.org/Archives/Public/public-script-coord/2013JulSep/0430.html) that prefixing with `_` should be enough to distinguish a namespace that web devs could use without fear of stepping on future web standards.

It has not received valid criticism.

**Comment by triblondon** [comment]
I won't weigh in on how valid the criticism is, but it looks like it's received a lot of feedback!  I'd say that an underscore prefix would be a good example of adhering to our recommendation here, and I'm not sure there's any need for the TAG finding to specifically assign a particular namespace for non-standard stuff (which would in any case leave us in bikeshed hell until the end of time).

**Comment by triblondon** [comment]
@DavidBruant I think it's overwhelmingly likely that other TAG members will agree with me that we should not be trying to own a namespace via a TAG finding.  If you want me to take it to the group anyway I'll do it, but otherwise let's focus on your other issues.
