### ISSUE TITLE
About rAF

### ISSUE THREAD

**Issue by torgo** [w3ctag/polyfills#25]
From #8 

- The example of implementor adoption of prefixed APIs is a distraction (and not directly relevant) to the setup of the polyfill risk point made in this section: a polyfill expecting a "fantasy" standard version of their prefixed utility which behavior is unknown/expected to be the same as the polyfill. I think Example 3 and the build-up to it could be dropped without impacting the points made later.

**Comment by triblondon** [comment]
Removing this part
